### ISSUE TITLE
Unhandled NullReferenceException

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.Tradier#32]
#### Expected Behavior
LEAN runs without `NullReferenceException`.

#### Actual Behavior

```
2024-04-26T08:00:41.5926068Z TRACE:: CloudLiveTradingResultHandler.BrokerageMessage(): Error - Code: Unauthorized - Required scope(s): scope-stream.scopeSet - Brokerage: TradierBrokerage
2024-04-26T08:00:41.5993643Z ERROR:: Extensions.SetRuntimeError(): Extensions.SetRuntimeError(): RuntimeError at 04/26/2024 08:00:40 UTC. Context: Brokerage Error System.Exception: Required scope(s): scope-stream.scopeSet
2024-04-26T08:00:41.7012011Z ERROR:: TradierBrokerage.a():  System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantConnect.Brokerages.Tradier.TradierBrokerage.c()
   at QuantConnect.Brokerages.Tradier.TradierBrokerage.a()
```

#### Potential Solution
N/A

#### Reproducing the Problem
An algorithm with universe selection similar to
https://quantpedia.com/strategies/trend-following-effect-in-stocks/

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Romazes** [comment]
The issue cannot be reproduced at this time, so we will close it for now. Please reopen if it occurs again, and we will address it as soon as possible.
